### ISSUE TITLE
When episode is named as Special, it detects as episode 1

### ISSUE THREAD

**Issue by tprivaterep** [moviecollection/movie-file-library#2]
Not.Going.Out.S11.Christmas.Special.1080p.HEVC.x265-MeGusta.mkv

![image](https://user-images.githubusercontent.com/102672045/175367302-f2c12905-bfb4-4c76-a57b-fdaa17e7882e.png)

Should detect as S00E11 as it's a special
Identifiable as there is no E after the S11

Can you please investigate, thank you

**Comment by peymanr34** [comment]
> Should detect as S00E11 as it's a special

I don't think that's right. In this case the episode number should be `null`:

**Expected:**
```
{
  Title: Not Going Out,
  IsSeries: true,
  Season: 11,
  IsSuccess: true,
}
```

**Actual:**
```
{
  Title: Not Going Out,
  IsSeries: true,
  Season: 11,
  Episode: 1,
  IsSuccess: true,
}
```

**Comment by tprivaterep** [comment]
Happy with that :)

**Comment by tprivaterep** [comment]
Sorry, need to recomment.
I think Season should be null and Episode the number.

Reason I say this, in the example what if the show has a season 11 then the special is point to season 11 episode 1 where in reality it's tracked as Season 0 or Specials, episode 11

Here's an example of how TheTVDB tracks, and most places that track episodes use this site and it's API
https://thetvdb.com/series/supernatural/allseasons/official

**Comment by peymanr34** [comment]
I think this library should provide the extracted information as-is; Similarly [guessit](https://github.com/guessit-io/guessit) has the exact same behavior.

```bash
guessit "Not.Going.Out.S11.Christmas.Special.1080p.HEVC.x265-MeGusta.mkv"
```
```
GuessIt found: {
    "title": "Not Going Out",
    "season": 11,
    "episode_title": "Christmas Special",
    "episode_details": "Special",
    "screen_size": "1080p",
    "video_codec": "H.265",
    "video_profile": "High Efficiency Video Coding",
    "release_group": "MeGusta",
    "container": "mkv",
    "mimetype": "video/x-matroska",
    "type": "episode"
}
```

I might add a `IsSpecialEpisode` property so that you can handle this in your application.

**Comment by tprivaterep** [comment]
That sounds like a good compromise :)
